#!/usr/bin/env bash

set -e
# set -x

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

PATH=/usr/local/bin:$PATH

payload=$(mktemp /tmp/payload.XXXXXX)
response=$(mktemp /tmp/response.XXXXXX)

source=$1

cat > $payload <&0

endpoint=$(jq -r '.source.url' < $payload)
oauth=$(jq -r '.source.oauth' < $payload)
status=$(jq -r '.params.status' < $payload)

curl -s -H "Authorization: OAuth ${oauth}" -X PATCH -d "component[status]=${status}" $endpoint > $response

cat < $response >&3

rm $payload
